export default {
  FILES: 'file',
  TOGGLE: 'toggle',
  PANEL: 'panel',
  INLINE_PANEL: 'inline-panel',
  EXTERNAL_MODAL: 'external-modal',
  DROPDOWN: 'dropdown',
  SEPARATOR: 'separator',
  SIZE_ORIGINAL: 'size-original',
  SIZE_SMALL_CENTER: 'size-small-center',
  SIZE_SMALL_LEFT: 'size-small-left',
  SIZE_SMALL_RIGHT: 'size-small-right',
  SIZE_CONTENT: 'size-content',
  SIZE_FULL_WIDTH: 'size-full-width',
  SIZE_SMALL: 'size-small',
  SIZE_MEDIUM: 'size-medium',
  SIZE_LARGE: 'size-large',
  ALIGNMENT_LEFT: 'alignment-left',
  ALIGNMENT_CENTER: 'alignment-center',
  ALIGNMENT_RIGHT: 'alignment-right',
  WIDTH: 'width',
  HEIGHT: 'height',
  LINK: 'link',
  DELETE: 'delete',
};
